import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { formatPrice } from '@/data/catalog';
import { CatalogFeedback } from '@/components/catalog-feedback';
import { useCatalog } from '@/state/catalog';
import { useCart } from '@/state/cart';

export default function ProductScreen(){
  const {shopSlug,productSlug}=useLocalSearchParams<{shopSlug:string;productSlug:string}>();const router=useRouter();const {products,status,refresh}=useCatalog();const {add}=useCart();const [favorite,setFavorite]=useState(false);const [added,setAdded]=useState(false);const product=products.find(item=>item.shopSlug===shopSlug&&item.slug===productSlug);
  if(status!=='ready')return <SafeAreaView style={s.safe}><View style={s.state}><CatalogFeedback status={status} onRetry={refresh}/></View></SafeAreaView>;
  if(!product)return <SafeAreaView style={s.safe}><View style={s.notFound}><Text style={s.notFoundTitle}>Produit indisponible.</Text><Text style={s.notFoundCopy}>Il n’est plus publié ou son adresse est incorrecte.</Text><Pressable onPress={()=>router.replace('/(tabs)/explore')}><Text style={s.back}>Retour au catalogue</Text></Pressable></View></SafeAreaView>;
  const available=product.stock>0;
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><View style={s.top}><Pressable accessibilityRole="button" accessibilityLabel="Retour" style={s.round} onPress={()=>router.back()}><Text>←</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={favorite?'Retirer des favoris':'Ajouter aux favoris'} style={[s.round,favorite&&s.favorite]} onPress={()=>setFavorite(value=>!value)}><Text style={favorite&&s.favoriteText}>{favorite?'♥':'♡'}</Text></Pressable></View><View style={[s.visual,{backgroundColor:product.color}]}><View style={s.controlled}><Text style={s.controlledText}>✓ PREUVE REVUE</Text></View><View style={s.bottle}/></View><Text style={s.shop}>{product.shop.toUpperCase()}</Text><Text style={s.title}>{product.name}</Text><View style={s.priceRow}><Text style={s.price}>{formatPrice(product.price,product.currency)}</Text><Text style={[s.stock,!available&&s.outOfStock]}>● {available?`${product.stock} disponible${product.stock>1?'s':''}`:'Indisponible'}</Text></View><Text style={s.description}>{product.description}</Text><View style={s.line}><Text style={s.label}>FORMAT</Text><Text style={s.value}>{product.format}</Text></View><View style={s.line}><Text style={s.label}>VENDU ET EXPÉDIÉ PAR</Text><Text style={s.value}>{product.shop}</Text></View><View style={s.trust}><Text style={s.trustOverline}>POURQUOI CE PRODUIT EST VISIBLE</Text><Text style={s.summary}>{product.verificationSummary}</Text><View style={s.trustRow}><Text style={s.trustLabel}>Périmètre</Text><Text style={s.trustText}>{product.evidence.scope}</Text></View><View style={s.trustRow}><Text style={s.trustLabel}>Nature</Text><Text style={s.trustText}>{product.evidence.kind.replaceAll('_',' ')}</Text></View><View style={s.trustRow}><Text style={s.trustLabel}>Émetteur</Text><Text style={s.trustText}>{product.evidence.issuerName??'Déclaration documentée du vendeur'}</Text></View>{product.evidence.referenceNumber&&<View style={s.trustRow}><Text style={s.trustLabel}>Référence</Text><Text style={s.trustText}>{product.evidence.referenceNumber}</Text></View>}<Pressable onPress={()=>router.push({pathname:'/account/[section]',params:{section:'trust'}})}><Text style={s.learn}>Comprendre notre méthode →</Text></Pressable></View><Pressable disabled={!available} style={[s.cta,added&&s.added,!available&&s.disabled]} onPress={()=>{add(product);setAdded(true)}}><Text style={s.ctaText}>{!available?'INDISPONIBLE':added?'✓ AJOUTÉ — AJOUTER ENCORE':'AJOUTER AU PANIER  →'}</Text></Pressable>{added&&<Pressable style={s.viewCart} onPress={()=>router.push('/cart')}><Text style={s.viewCartText}>VOIR MON PANIER</Text></Pressable>}<Text style={s.reassurance}>Paiement et commande désactivés dans cette version de développement.</Text></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#eee6d9'},page:{padding:20,paddingBottom:60},state:{flex:1,justifyContent:'center',padding:20},top:{marginTop:5,flexDirection:'row',justifyContent:'space-between'},round:{width:40,height:40,borderRadius:20,borderWidth:1,borderColor:'#17201c30',alignItems:'center',justifyContent:'center'},favorite:{backgroundColor:'#092b5d'},favoriteText:{color:'white'},visual:{height:350,marginTop:16,alignItems:'center',justifyContent:'center'},controlled:{position:'absolute',left:12,top:12,paddingHorizontal:9,paddingVertical:7,backgroundColor:'#eee6d9'},controlledText:{fontSize:7,fontWeight:'900',color:'#285b48'},bottle:{width:88,height:175,borderRadius:42,backgroundColor:'#263b33'},shop:{marginTop:25,fontSize:9,letterSpacing:1.4,color:'#687069'},title:{marginTop:8,fontSize:42,fontWeight:'900',letterSpacing:-2.4},priceRow:{marginTop:12,flexDirection:'row',alignItems:'center'},price:{fontSize:20,fontWeight:'800'},stock:{marginLeft:'auto',fontSize:9,color:'#2d654e'},outOfStock:{color:'#9a4c3a'},description:{marginTop:22,fontSize:13,lineHeight:22,color:'#5f665f'},line:{marginTop:18,paddingVertical:15,borderTopWidth:1,borderTopColor:'#17201c2d',flexDirection:'row'},label:{fontSize:8,fontWeight:'800',letterSpacing:1.1},value:{marginLeft:'auto',maxWidth:'55%',fontSize:10,fontWeight:'700',textAlign:'right'},trust:{marginTop:20,padding:20,backgroundColor:'#e0d5c3'},trustOverline:{fontSize:8,fontWeight:'900',letterSpacing:1.2},summary:{marginTop:12,fontSize:12,lineHeight:19,fontWeight:'700'},trustRow:{marginTop:14,paddingTop:12,borderTopWidth:1,borderTopColor:'#17201c20'},trustLabel:{fontSize:8,fontWeight:'900',letterSpacing:1,color:'#687069'},trustText:{marginTop:4,fontSize:11,lineHeight:17},learn:{marginTop:18,fontSize:9,fontWeight:'800',textDecorationLine:'underline'},cta:{marginTop:20,padding:18,borderRadius:9,backgroundColor:'#ef6b38',alignItems:'center'},added:{backgroundColor:'#28614b'},disabled:{opacity:.4},ctaText:{color:'white',fontSize:10,fontWeight:'900'},viewCart:{marginTop:9,padding:15,borderWidth:1,borderColor:'#17201c',alignItems:'center'},viewCartText:{fontSize:10,fontWeight:'900'},reassurance:{marginTop:13,textAlign:'center',fontSize:8,color:'#717872'},notFound:{flex:1,padding:30,alignItems:'center',justifyContent:'center'},notFoundTitle:{fontSize:24,fontWeight:'900'},notFoundCopy:{marginTop:8,fontSize:11,color:'#687069',textAlign:'center'},back:{marginTop:20,textDecorationLine:'underline'}});
