import Link from "next/link";
import { redirect } from "next/navigation";
import { getViewer } from "@/lib/auth/dal";
import { getModerationQueue } from "@/lib/moderation/dal";
import { getSupabaseConfig } from "@/lib/supabase/config";
import { reviewProductAction, reviewShopAction } from "./actions";

export const dynamic = "force-dynamic";
const money = new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" });

export default async function ModerationPage({ searchParams }: { searchParams: Promise<{ reviewed?: string; error?: string }> }) {
  if (!getSupabaseConfig()) redirect("/");
  const [viewer, queue, params] = await Promise.all([getViewer(), getModerationQueue(), searchParams]);
  if (!viewer || !queue || (viewer.role !== "operator" && viewer.role !== "admin")) redirect("/");

  return <main className="moderation-shell"><header className="moderation-topbar"><Link href="/" className="brand-mark">yaqeen<span>✦</span></Link><b>OPÉRATIONS · MODÉRATION</b><div><span>{viewer.role}</span><Link href="/compte">{viewer.displayName || viewer.email || "Opérateur"}</Link></div></header><section className="moderation-hero"><p>FILE DE DÉCISION RÉELLE</p><h1>Établir avant<br /><span>de publier.</span></h1><div><strong>{queue.shops.length + queue.products.length}</strong><span>soumission{queue.shops.length + queue.products.length > 1 ? "s" : ""} à examiner</span></div></section>
    {params.reviewed && <div className="moderation-flash">✓ Décision enregistrée dans le journal de modération.</div>}{params.error && <div className="moderation-flash moderation-flash-error">La transition a été refusée. Vérifiez les champs et l’état courant.</div>}
    <section className="moderation-section"><header><div><p>01 · BOUTIQUES</p><h2>Identité professionnelle</h2></div><span>{queue.shops.length} en attente</span></header>{queue.shops.length === 0 ? <p className="moderation-empty">Aucune boutique en attente de revue.</p> : <div className="moderation-grid">{queue.shops.map((shop) => <article className="moderation-card" key={shop.id}><div className="moderation-card-head"><span>BO</span><div><h3>{shop.name}</h3><p>/{shop.slug} · {shop.country}</p></div></div><p className="moderation-description">{shop.description}</p><form action={reviewShopAction} className="moderation-form"><input type="hidden" name="shopId" value={shop.id} /><label>Motif de la décision<textarea name="rationale" required minLength={10} maxLength={2000} rows={3} placeholder="Contrôles effectués, limites et justification…" /></label><div><button name="decision" value="rejected" className="moderation-reject">Refuser</button><button name="decision" value="approved" className="moderation-approve">Approuver la boutique</button></div></form></article>)}</div>}</section>
    <section className="moderation-section moderation-products"><header><div><p>02 · PRODUITS & PREUVES</p><h2>Périmètre de confiance</h2></div><span>{queue.products.length} en attente</span></header>{queue.products.length === 0 ? <p className="moderation-empty">Aucun produit en attente de revue.</p> : <div className="moderation-grid">{queue.products.map((product) => <article className="moderation-card" key={product.id}><div className="moderation-card-head"><span>PR</span><div><h3>{product.title}</h3><p>{product.shopName} · {product.category}</p></div></div><p className="moderation-description">{product.description}</p><dl><div><dt>Variante</dt><dd>{product.variant ? `${product.variant.title} · ${product.variant.sku}` : "Absente"}</dd></div><div><dt>Prix / stock</dt><dd>{product.variant ? `${money.format(product.variant.priceCents / 100)} · ${product.variant.stock}` : "—"}</dd></div><div><dt>Nature</dt><dd>{product.evidence?.kind ?? "Absente"}</dd></div><div><dt>Périmètre déclaré</dt><dd>{product.evidence?.scope ?? "—"}</dd></div><div><dt>Émetteur / référence</dt><dd>{product.evidence?.issuerName || "Déclaration vendeur"} · {product.evidence?.referenceNumber || "sans référence"}</dd></div></dl>{product.evidence ? <form action={reviewProductAction} className="moderation-form"><input type="hidden" name="productId" value={product.id} /><input type="hidden" name="evidenceId" value={product.evidence.id} /><label>Résumé public validé<textarea name="publicSummary" defaultValue={product.evidence.proposedSummary ?? ""} maxLength={1000} rows={3} placeholder="Obligatoire en cas d’approbation…" /></label><label>Motif interne<textarea name="rationale" required minLength={10} maxLength={2000} rows={3} placeholder="Contrôles effectués et justification…" /></label><div><button name="decision" value="rejected" className="moderation-reject">Refuser</button><button name="decision" value="approved" className="moderation-approve">Approuver et publier</button></div></form> : <p className="moderation-blocked">Décision impossible : aucune preuve en attente.</p>}</article>)}</div>}</section>
  </main>;
}
