import { useLocalSearchParams, useRouter } from 'expo-router';
import { Image } from 'expo-image';
import { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { categories, formatPrice, productRoute } from '@/data/catalog';
import { useCatalog } from '@/state/catalog';
import { CatalogFeedback } from '@/components/catalog-feedback';
import { MarketHeader } from '@/components/market-header';

export default function ExploreScreen(){
  const params=useLocalSearchParams<{category?:string}>();const router=useRouter();const {products,status,refresh}=useCatalog();const [query,setQuery]=useState('');const [category,setCategory]=useState(params.category||'Tous');
  const results=useMemo(()=>products.filter(product=>(category==='Tous'||product.category===category)&&(`${product.name} ${product.shop}`).toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr'))),[category,products,query]);
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page} keyboardShouldPersistTaps="handled"><MarketHeader/><Text style={s.kicker}>EXPLORER YAQEEN</Text><Text style={s.title}>TROUVEZ VOTRE{`\n`}PROCHAINE <Text style={s.accent}>MAISON.</Text></Text><View style={s.search}><Text style={s.searchIcon}>⌕</Text><TextInput value={query} onChangeText={setQuery} autoCapitalize="none" placeholder="Produit ou boutique…" placeholderTextColor="#747b75" style={s.input}/>{query.length>0&&<Pressable accessibilityLabel="Effacer la recherche" onPress={()=>setQuery('')}><Text style={s.clear}>×</Text></Pressable>}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{categories.map(item=><Pressable key={item} onPress={()=>setCategory(item)} style={[s.filter,category===item&&s.filterActive]}><Text style={[s.filterText,category===item&&s.filterTextActive]}>{item}</Text></Pressable>)}</ScrollView><View style={s.resultHead}><Text style={s.count}>{status==='ready'?`${results.length} RÉSULTAT${results.length>1?'S':''}`:'CATALOGUE'}</Text><Text style={s.hint}>Preuves & médias revus</Text></View>{status!=='ready'?<CatalogFeedback status={status} onRetry={refresh}/>:results.length===0?<View style={s.empty}><Text style={s.emptyTitle}>{products.length===0?'Aucun produit publié.':'Aucun résultat.'}</Text><Text style={s.emptyCopy}>{products.length===0?'Le catalogue se remplit uniquement après revue.':'Essayez une autre recherche ou revenez à toutes les catégories.'}</Text>{products.length>0&&<Pressable onPress={()=>{setQuery('');setCategory('Tous')}} style={s.reset}><Text style={s.resetText}>EFFACER LES FILTRES</Text></Pressable>}</View>:<View style={s.grid}>{results.map(product=><Pressable key={product.id} style={s.product} onPress={()=>router.push(productRoute(product))}><View style={s.visual}><Image source={product.media[0].url} alt={product.media[0].altText} style={s.productImage} contentFit="cover" cachePolicy="memory-disk" transition={180}/></View><Text style={s.shop}>{product.shop}</Text><Text style={s.name}>{product.name}</Text><Text style={s.price}>{formatPrice(product.price,product.currency)}</Text></Pressable>)}</View>}</ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#eee6d9'},page:{padding:20,paddingBottom:95},kicker:{marginTop:20,fontSize:9,fontWeight:'800',letterSpacing:1.7,color:'#687069'},title:{marginTop:13,fontSize:40,lineHeight:38,fontWeight:'900',letterSpacing:-2.5,color:'#17201c'},accent:{color:'#ef6b38'},search:{marginTop:25,minHeight:54,paddingHorizontal:15,borderRadius:11,backgroundColor:'#e0d5c3',flexDirection:'row',alignItems:'center'},searchIcon:{fontSize:18},input:{flex:1,marginLeft:11,fontSize:13,color:'#17201c'},clear:{fontSize:24,color:'#59615b'},filters:{gap:7,paddingVertical:15},filter:{paddingHorizontal:14,paddingVertical:9,borderRadius:22,borderWidth:1,borderColor:'#17201c2d'},filterActive:{backgroundColor:'#092b5d',borderColor:'#092b5d'},filterText:{fontSize:10,fontWeight:'700'},filterTextActive:{color:'white'},resultHead:{marginTop:16,paddingBottom:12,borderBottomWidth:1,borderColor:'#17201c2d',flexDirection:'row'},count:{fontSize:8,fontWeight:'900',letterSpacing:1.3},hint:{marginLeft:'auto',fontSize:8,color:'#687069'},grid:{marginTop:14,flexDirection:'row',flexWrap:'wrap',gap:10},product:{width:'48%'},visual:{height:190,overflow:'hidden'},productImage:{width:'100%',height:'100%'},shop:{marginTop:9,fontSize:8,color:'#6d746e'},name:{marginTop:4,fontSize:14,fontWeight:'800'},price:{marginTop:7,fontSize:11,fontWeight:'800'},empty:{marginTop:45,padding:25,backgroundColor:'#e0d5c3'},emptyTitle:{fontSize:20,fontWeight:'800'},emptyCopy:{marginTop:10,fontSize:11,lineHeight:18,color:'#666d67'},reset:{marginTop:20,alignSelf:'flex-start',paddingVertical:11,paddingHorizontal:14,backgroundColor:'#17201c'},resetText:{color:'white',fontSize:9,fontWeight:'900'}});
