import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { products } from '@/data/products';
import { MarketHeader } from '@/components/market-header';

export default function HomeScreen(){const router=useRouter();const goExplore=(category?:string)=>router.push({pathname:'/(tabs)/explore',params:category?{category}:undefined});return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
  <MarketHeader />
  <Text style={s.eyebrow}>LA SÉLECTION DE LA COMMUNAUTÉ</Text><Text style={s.title}>ACHETEZ AUPRÈS{`\n`}DE MAISONS DE <Text style={s.accent}>CONFIANCE.</Text></Text>
  <Pressable accessibilityRole="search" style={s.search} onPress={()=>goExplore()}><Text style={s.searchIcon}>⌕</Text><View><Text style={s.searchLabel}>Que recherchez-vous ?</Text><Text style={s.muted}>Produit, boutique ou catégorie</Text></View><Text style={s.arrow}>→</Text></Pressable>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{['Parfums','Livres','Soins','Mode','Bien-être'].map(item=><Pressable style={s.chip} key={item} onPress={()=>goExplore(item)}><Text style={s.chipText}>{item}</Text></Pressable>)}</ScrollView>
  <View style={s.sectionHead}><View><Text style={s.sectionOverline}>NOUVEAUTÉS</Text><Text style={s.sectionTitle}>À découvrir</Text></View><Pressable onPress={()=>goExplore()}><Text style={s.link}>Tout explorer →</Text></Pressable></View>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.productRail}>{products.map(product=><Pressable style={s.product} key={product.name} onPress={()=>router.push({pathname:'/product/[slug]',params:{slug:product.slug}})}><View style={[s.visual,{backgroundColor:product.color}]}><View style={s.verified}><Text style={s.verifiedText}>✓ CONTRÔLÉ</Text></View><View style={s.bottle}/></View><Text style={s.shop}>{product.shop.toUpperCase()}</Text><Text style={s.productName}>{product.name}</Text><View style={s.productFoot}><Text style={s.price}>{product.price} €</Text><Text style={s.productArrow}>↗</Text></View></Pressable>)}</ScrollView>
  <Pressable style={s.trustCard} onPress={()=>router.push({pathname:'/account/[section]',params:{section:'trust'}})}><Text style={s.trustOverline}>LA CONFIANCE, LISIBLE</Text><Text style={s.trustTitle}>Comprendre pourquoi un produit est présent sur Yaqeen.</Text><Text style={s.trustCopy}>Identité vendeur, documents produit et informations de livraison réunis au même endroit.</Text><Text style={s.trustLink}>Découvrir notre méthode →</Text></Pressable>
</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#eee6d9'},page:{paddingHorizontal:18,paddingBottom:95},header:{height:64,flexDirection:'row',alignItems:'center'},logo:{fontSize:27,fontWeight:'900',letterSpacing:-2,color:'#17201c'},dot:{color:'#ef6b38',fontSize:17},headerActions:{marginLeft:'auto',flexDirection:'row',gap:8},round:{width:38,height:38,borderWidth:1,borderColor:'#17201c33',borderRadius:19,alignItems:'center',justifyContent:'center'},alertDot:{position:'absolute',top:8,right:8,width:6,height:6,borderRadius:3,backgroundColor:'#ef6b38'},cartButton:{width:38,height:38,borderRadius:19,backgroundColor:'#092b5d',alignItems:'center',justifyContent:'center'},cartIcon:{color:'white'},badge:{position:'absolute',top:-4,right:-3,minWidth:17,height:17,paddingHorizontal:4,borderRadius:9,backgroundColor:'#ef6b38',color:'white',fontSize:9,fontWeight:'900',textAlign:'center',lineHeight:17},eyebrow:{marginTop:20,fontSize:9,fontWeight:'800',letterSpacing:1.6,color:'#687069'},title:{marginTop:13,fontSize:40,lineHeight:38,fontWeight:'900',letterSpacing:-2.5,color:'#17201c'},accent:{color:'#ef6b38'},search:{marginTop:25,minHeight:66,paddingHorizontal:16,borderRadius:12,backgroundColor:'#17201c',flexDirection:'row',alignItems:'center'},searchIcon:{marginRight:13,color:'white',fontSize:20},searchLabel:{color:'white',fontSize:13,fontWeight:'800'},muted:{marginTop:3,fontSize:9,color:'#aab1ac'},arrow:{marginLeft:'auto',color:'#ef6b38',fontSize:18},chips:{gap:7,paddingVertical:15},chip:{paddingHorizontal:14,paddingVertical:10,borderWidth:1,borderColor:'#17201c28',borderRadius:22},chipText:{fontSize:10,fontWeight:'600',color:'#17201c'},sectionHead:{marginTop:22,flexDirection:'row',alignItems:'flex-end'},sectionOverline:{fontSize:8,fontWeight:'800',letterSpacing:1.4,color:'#737a74'},sectionTitle:{marginTop:4,fontSize:22,fontWeight:'900',letterSpacing:-.8},link:{fontSize:10,fontWeight:'700',textDecorationLine:'underline'},productRail:{gap:11,paddingTop:14,paddingRight:18},product:{width:155},visual:{height:188,alignItems:'center',justifyContent:'center'},verified:{position:'absolute',left:9,top:9,paddingHorizontal:7,paddingVertical:5,backgroundColor:'#eee6d9'},verifiedText:{fontSize:7,fontWeight:'900',color:'#285b48'},bottle:{width:45,height:92,borderRadius:22,backgroundColor:'#263b33'},shop:{marginTop:10,fontSize:8,color:'#6d746e'},productName:{marginTop:4,fontSize:14,fontWeight:'800'},productFoot:{marginTop:8,flexDirection:'row'},price:{fontSize:11,fontWeight:'800'},productArrow:{marginLeft:'auto'},trustCard:{marginTop:38,padding:24,backgroundColor:'#092b5d'},trustOverline:{fontSize:8,fontWeight:'800',letterSpacing:1.5,color:'#9fb0c8'},trustTitle:{marginTop:14,fontSize:23,lineHeight:26,fontWeight:'800',letterSpacing:-1,color:'#f0e8dc'},trustCopy:{marginTop:14,fontSize:11,lineHeight:18,color:'#b9c4d3'},trustLink:{marginTop:20,color:'#ef8a61',fontSize:10,fontWeight:'800'}});
