import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Image } from 'expo-image';
import { categories, formatPrice, productRoute } from '@/data/catalog';
import { useCatalog } from '@/state/catalog';
import { MarketHeader } from '@/components/market-header';
import { CatalogFeedback } from '@/components/catalog-feedback';

export default function HomeScreen(){
  const router=useRouter();const {products,status,refresh}=useCatalog();
  const goExplore=(category?:string)=>router.push({pathname:'/(tabs)/explore',params:category?{category}:undefined});
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
    <MarketHeader />
    <Text style={s.eyebrow}>PAR LA COMMUNAUTÉ · POUR LA COMMUNAUTÉ</Text><Text style={s.title}>ACHETEZ AUPRÈS{`\n`}DE MAISONS DE <Text style={s.accent}>CONFIANCE.</Text></Text>
    <Pressable accessibilityRole="search" style={s.search} onPress={()=>goExplore()}><Text style={s.searchIcon}>⌕</Text><View><Text style={s.searchLabel}>Que recherchez-vous ?</Text><Text style={s.muted}>Produit, boutique ou catégorie</Text></View><Text style={s.arrow}>→</Text></Pressable>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{categories.slice(1,6).map(item=><Pressable style={s.chip} key={item} onPress={()=>goExplore(item)}><Text style={s.chipText}>{item}</Text></Pressable>)}</ScrollView>
    <View style={s.sectionHead}><View><Text style={s.sectionOverline}>DERNIÈRES PUBLICATIONS</Text><Text style={s.sectionTitle}>À découvrir</Text></View><Pressable onPress={()=>goExplore()}><Text style={s.link}>Tout explorer →</Text></Pressable></View>
    {status!=='ready'||products.length===0?<CatalogFeedback status={status} onRetry={refresh}/>:<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.productRail}>{products.slice(0,8).map(product=><Pressable style={s.product} key={product.id} onPress={()=>router.push(productRoute(product))}><View style={s.visual}><Image source={product.media[0].url} alt={product.media[0].altText} style={s.productImage} contentFit="cover" cachePolicy="memory-disk" transition={180}/><View style={s.verified}><Text style={s.verifiedText}>✓ REVUE YAQEEN</Text></View></View><Text style={s.shop}>{product.shop.toUpperCase()}</Text><Text style={s.productName}>{product.name}</Text><View style={s.productFoot}><Text style={s.price}>{formatPrice(product.price,product.currency)}</Text><Text style={s.productArrow}>↗</Text></View></Pressable>)}</ScrollView>}
    <Pressable style={s.trustCard} onPress={()=>router.push({pathname:'/account/[section]',params:{section:'trust'}})}><Text style={s.trustOverline}>LA CONFIANCE, LISIBLE</Text><Text style={s.trustTitle}>Comprendre pourquoi un produit est présent sur Yaqeen.</Text><Text style={s.trustCopy}>Une boutique approuvée, une fiche publiée et le périmètre exact de la preuve revue — sans notation inventée.</Text><Text style={s.trustLink}>Découvrir notre méthode →</Text></Pressable>
  </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#eee6d9'},page:{paddingHorizontal:18,paddingBottom:95},eyebrow:{marginTop:20,fontSize:9,fontWeight:'800',letterSpacing:1.6,color:'#687069'},title:{marginTop:13,fontSize:40,lineHeight:38,fontWeight:'900',letterSpacing:-2.5,color:'#17201c'},accent:{color:'#ef6b38'},search:{marginTop:25,minHeight:66,paddingHorizontal:16,borderRadius:12,backgroundColor:'#17201c',flexDirection:'row',alignItems:'center'},searchIcon:{marginRight:13,color:'white',fontSize:20},searchLabel:{color:'white',fontSize:13,fontWeight:'800'},muted:{marginTop:3,fontSize:9,color:'#aab1ac'},arrow:{marginLeft:'auto',color:'#ef6b38',fontSize:18},chips:{gap:7,paddingVertical:15},chip:{paddingHorizontal:14,paddingVertical:10,borderWidth:1,borderColor:'#17201c28',borderRadius:22},chipText:{fontSize:10,fontWeight:'600',color:'#17201c'},sectionHead:{marginTop:22,flexDirection:'row',alignItems:'flex-end'},sectionOverline:{fontSize:8,fontWeight:'800',letterSpacing:1.4,color:'#737a74'},sectionTitle:{marginTop:4,fontSize:22,fontWeight:'900',letterSpacing:-.8},link:{fontSize:10,fontWeight:'700',textDecorationLine:'underline'},productRail:{gap:11,paddingTop:14,paddingRight:18},product:{width:155},visual:{height:188,overflow:'hidden'},productImage:{width:'100%',height:'100%'},verified:{position:'absolute',left:9,top:9,paddingHorizontal:7,paddingVertical:5,backgroundColor:'#eee6d9'},verifiedText:{fontSize:7,fontWeight:'900',color:'#285b48'},shop:{marginTop:10,fontSize:8,color:'#6d746e'},productName:{marginTop:4,fontSize:14,fontWeight:'800'},productFoot:{marginTop:8,flexDirection:'row'},price:{fontSize:11,fontWeight:'800'},productArrow:{marginLeft:'auto'},trustCard:{marginTop:38,padding:24,backgroundColor:'#092b5d'},trustOverline:{fontSize:8,fontWeight:'800',letterSpacing:1.5,color:'#9fb0c8'},trustTitle:{marginTop:14,fontSize:23,lineHeight:26,fontWeight:'800',letterSpacing:-1,color:'#f0e8dc'},trustCopy:{marginTop:14,fontSize:11,lineHeight:18,color:'#b9c4d3'},trustLink:{marginTop:20,color:'#ef8a61',fontSize:10,fontWeight:'800'}});
