"use client";
import Link from "next/link";
import { useCart } from "./cart-provider";
import { formatPrice } from "@/data/products";

export function CartPage(){
  const {items,count,subtotal,update,remove}=useCart();const shipping=subtotal>=59||subtotal===0?0:4.9;const total=subtotal+shipping;const shops=new Set(items.map(i=>i.shop)).size;
  return <main className="cart-shell"><header className="market-nav"><Link href="/" className="brand-mark">yaqeen<span>✦</span></Link><Link href="/catalogue" className="back-catalog">← Continuer mes achats</Link><nav><span>Panier</span><b className="cart-count">{count}</b></nav></header>
    <section className="cart-title"><p>VOTRE COMMANDE</p><h1>Votre panier<span>.</span></h1><small>{count} {count>1?"produits":"produit"} · {shops} {shops>1?"vendeurs":"vendeur"}</small></section>
    {items.length===0?<section className="cart-empty"><div>◇</div><h2>Votre panier est vide.</h2><p>Découvrez les produits proposés par nos vendeurs.</p><Link href="/catalogue">Voir le catalogue →</Link></section>:<section className="cart-layout"><div className="cart-items">{items.map(item=><article className="cart-item" key={item.slug}><Link href={`/produit/${item.slug}`} className="cart-item-visual" style={{backgroundColor:item.color}}><div className={`catalog-object ${item.shape}`}>Y</div></Link><div className="cart-item-copy"><p>Vendu par {item.shop}</p><Link href={`/produit/${item.slug}`}>{item.name}</Link><span>Format standard</span><div className="cart-item-actions"><div><button onClick={()=>update(item.slug,item.quantity-1)}>−</button><span>{item.quantity}</span><button onClick={()=>update(item.slug,item.quantity+1)}>＋</button></div><button onClick={()=>remove(item.slug)}>Retirer</button></div></div><strong>{formatPrice(item.price*item.quantity)}</strong></article>)}</div><aside className="cart-summary"><p>RÉCAPITULATIF</p><h2>Votre commande</h2><dl><div><dt>Sous-total</dt><dd>{formatPrice(subtotal)}</dd></div><div><dt>Livraison</dt><dd>{shipping===0?"Offerte":formatPrice(shipping)}</dd></div></dl>{subtotal<59&&<div className="shipping-progress"><p>Plus que <strong>{formatPrice(59-subtotal)}</strong> pour la livraison offerte</p><span><i style={{width:`${Math.min(100,subtotal/59*100)}%`}}/></span></div>}<div className="cart-total"><span>Total</span><strong>{formatPrice(total)}</strong></div><button className="checkout-button">Passer au paiement →</button><small>Paiement sécurisé · CB · PayPal · Apple Pay</small><div className="cart-promise"><span>✓</span><p><strong>Achat protégé par Yaqeen</strong><br/>Vendeurs vérifiés et accompagnement en cas de problème.</p></div></aside></section>}
  </main>
}
