import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { formatPrice, productRoute } from '@/data/catalog';
import { useCart } from '@/state/cart';
import { MarketHeader } from '@/components/market-header';

export default function CartScreen(){
  const router=useRouter();const {items,total,count,add,decrement,remove}=useCart();const shops=new Set(items.map(item=>item.product.shop)).size;
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><MarketHeader/><View style={s.head}><View><Text style={s.kicker}>VOTRE PANIER</Text><Text style={s.title}>{count} ARTICLE{count>1?'S':''}</Text></View>{items.length>0&&<Text style={s.shops}>{shops} boutique{shops>1?'s':''}</Text>}</View>{items.length===0?<View style={s.empty}><Text style={s.emptyIcon}>▱</Text><Text style={s.emptyTitle}>Votre panier est vide.</Text><Text style={s.meta}>Parcourez le catalogue publié et ajoutez vos premières découvertes.</Text><Pressable style={s.discover} onPress={()=>router.push('/(tabs)/explore')}><Text style={s.discoverText}>EXPLORER LES PRODUITS →</Text></Pressable></View>:<>{Array.from(new Set(items.map(item=>item.product.shop))).map(shop=><View style={s.shopGroup} key={shop}><View style={s.shopHead}><View><Text style={s.shopOverline}>EXPÉDIÉ PAR</Text><Text style={s.shopName}>{shop}</Text></View><Text style={s.shopStatus}>✓ Boutique approuvée</Text></View>{items.filter(item=>item.product.shop===shop).map(line=><View style={s.item} key={line.product.id}><Pressable onPress={()=>router.push(productRoute(line.product))} style={[s.visual,{backgroundColor:line.product.color}]}><View style={s.bottle}/></Pressable><View style={s.copy}><Text style={s.name}>{line.product.name}</Text><Text style={s.meta}>{line.product.format}</Text><View style={s.controls}><Pressable accessibilityLabel="Diminuer la quantité" style={s.qty} onPress={()=>decrement(line.product.id)}><Text>−</Text></Pressable><Text style={s.quantity}>{line.quantity}</Text><Pressable disabled={line.quantity>=line.product.stock} accessibilityLabel="Augmenter la quantité" style={[s.qty,line.quantity>=line.product.stock&&s.qtyDisabled]} onPress={()=>add(line.product)}><Text>+</Text></Pressable><Pressable onPress={()=>remove(line.product.id)}><Text style={s.remove}>Supprimer</Text></Pressable></View></View><Text style={s.price}>{formatPrice(line.product.price*line.quantity,line.product.currency)}</Text></View>)}</View>)}</>}<View style={s.summary}><View style={s.summaryLine}><Text>Sous-total</Text><Text>{formatPrice(total)}</Text></View><View style={s.summaryLine}><Text>Livraison</Text><Text style={s.delivery}>À calculer par vendeur</Text></View><View style={s.total}><Text style={s.totalLabel}>Sous-total</Text><Text style={s.totalPrice}>{formatPrice(total)}</Text></View></View><Pressable style={[s.cta,s.disabled]} disabled><Text style={s.ctaText}>PAIEMENT BIENTÔT DISPONIBLE</Text></Pressable><Text style={s.note}>Aucune commande ni aucun paiement ne sont envoyés dans cette version.</Text></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#eee6d9'},page:{padding:20,paddingBottom:95},head:{marginTop:20,flexDirection:'row',alignItems:'flex-end'},kicker:{fontSize:9,fontWeight:'800',letterSpacing:1.7,color:'#687069'},title:{marginTop:5,fontSize:34,fontWeight:'900',letterSpacing:-1.8},shops:{marginLeft:'auto',fontSize:10,color:'#687069'},empty:{marginTop:35,padding:28,alignItems:'center',backgroundColor:'#e0d5c3'},emptyIcon:{fontSize:32},emptyTitle:{marginTop:15,fontSize:21,fontWeight:'800'},meta:{marginTop:5,fontSize:10,lineHeight:16,color:'#6d746e'},discover:{marginTop:22,padding:14,backgroundColor:'#092b5d'},discoverText:{color:'white',fontSize:9,fontWeight:'900'},shopGroup:{marginTop:26},shopHead:{paddingBottom:12,borderBottomWidth:1,borderColor:'#17201c2d',flexDirection:'row',alignItems:'flex-end'},shopOverline:{fontSize:7,fontWeight:'800',letterSpacing:1.3,color:'#737a74'},shopName:{marginTop:4,fontSize:16,fontWeight:'800'},shopStatus:{marginLeft:'auto',fontSize:8,color:'#28614b'},item:{paddingVertical:15,borderBottomWidth:1,borderColor:'#17201c20',flexDirection:'row',alignItems:'center',gap:13},visual:{width:72,height:88,alignItems:'center',justifyContent:'center'},bottle:{width:22,height:45,borderRadius:14,backgroundColor:'#263b33'},copy:{flex:1},name:{fontSize:15,fontWeight:'800'},controls:{marginTop:12,flexDirection:'row',alignItems:'center'},qty:{width:28,height:28,borderWidth:1,borderColor:'#17201c30',alignItems:'center',justifyContent:'center'},qtyDisabled:{opacity:.3},quantity:{width:30,textAlign:'center',fontSize:11,fontWeight:'800'},remove:{marginLeft:14,fontSize:9,textDecorationLine:'underline',color:'#747b75'},price:{fontSize:13,fontWeight:'800'},summary:{marginTop:28,padding:18,backgroundColor:'#e0d5c3'},summaryLine:{paddingVertical:6,flexDirection:'row',justifyContent:'space-between'},delivery:{fontSize:9,color:'#687069'},total:{marginTop:12,paddingTop:15,borderTopWidth:1,borderColor:'#17201c2d',flexDirection:'row',alignItems:'center'},totalLabel:{fontSize:12,fontWeight:'800'},totalPrice:{marginLeft:'auto',fontSize:24,fontWeight:'900'},cta:{marginTop:14,padding:17,borderRadius:9,backgroundColor:'#ef6b38',alignItems:'center'},disabled:{opacity:.4},ctaText:{color:'white',fontSize:10,fontWeight:'900'},note:{marginTop:12,textAlign:'center',fontSize:9,lineHeight:14,color:'#777d78'}});
